name: Add new client apikey
on:
  workflow_dispatch:
    inputs:
      revoke-access:
        type: boolean
        description: 'Revoke access'
        required: true

      client:
        description: 'ClientName'
        required: true

      email:
        description: 'Email'
        required: true

      plan:
        type: choice
        description: 'Plan'
        options:
          - unlimited
        default: unlimited

      apply-env-tst:
        type: boolean
        description: 'Test'
        required: true

      apply-env-stg:
        type: boolean
        description: 'Staging'
        required: true

      apply-env-prd:
        type: boolean
        description: 'Production'
        required: true

jobs:
  association-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add new client apikey (ik4)
        uses: ./action-add
        with:
          client: ${{ github.event.inputs.client }}
          email: ${{ github.event.inputs.email }}
          plan: ${{ github.event.inputs.plan }}

          env-tst: ${{ github.event.inputs.apply-env-tst }}
          env-stg: ${{ github.event.inputs.apply-env-stg }}
          env-prd: ${{ github.event.inputs.apply-env-prd }}
          
          aws-tst-access-key-id: ${{ secrets.AWS_TST_ACCESS_KEY_ID_IK_4 }}
          aws-stg-access-key-id: ${{ secrets.AWS_TST_ACCESS_KEY_ID_IK_4 }}
          aws-prd-access-key-id: ${{ secrets.AWS_TST_ACCESS_KEY_ID_IK_4 }}

          aws-tst-secret-access-key: ${{ secrets.AWS_TST_SECRET_ACCESS_KEY_IK_4 }}
          aws-stg-secret-access-key: ${{ secrets.AWS_TST_SECRET_ACCESS_KEY_IK_4 }}
          aws-prd-secret-access-key: ${{ secrets.AWS_TST_SECRET_ACCESS_KEY_IK_4 }}
          
          aws-tst-region-name: eu-west-1
          aws-stg-region-name: eu-west-1
          aws-prd-region-name: eu-west-1

          revoke-access: ${{ github.event.inputs.revoke-access }}
          