name: Remove client apikey
on:
  workflow_dispatch:
    inputs:
      api-key:
       description: 'Api Key'     
       required: true

      apply-env-tst:
        type: boolean
        description: 'Test'
        required: true

      apply-env-stg:
        type: boolean
        description: 'Staging'
        required: true
        
      apply-env-prd:
        type: boolean
        description: 'Production'
        required: true

jobs:
  association-registry:
    runs-on: ubuntu-latest
    steps:
    - name: remove client apikey
      uses: informatievlaanderen/association-registry-public-api-key-action/action-remove@main
      with:
          apikey: ${{github.event.inputs.api-key}}

          env-tst:  ${{ github.event.inputs.apply-env-tst }}
          env-stg:  ${{ github.event.inputs.apply-env-stg }}
          env-prd:  ${{ github.event.inputs.apply-env-prd }}
          
          aws-tst-tenant-id: ${{ secrets.AWS_TST_TENANT_ID }}
          aws-tst-access-key-id: ${{ secrets.AWS_TST_ACCESS_KEY_ID_IK_4 }}
          aws-tst-secret-access-key: ${{ secrets.AWS_TST_SECRET_ACCESS_KEY_IK_4 }}
          aws-tst-region-name: eu-west-1

          aws-stg-tenant-id: ${{ secrets.AWS_STG_TENANT_ID }}
          aws-stg-access-key-id: ${{ secrets.AWS_STG_ACCESS_KEY_ID_IK_4 }}
          aws-stg-secret-access-key: ${{ secrets.AWS_STG_SECRET_ACCESS_KEY_IK_4 }}
          aws-stg-region-name: eu-west-1

          aws-prd-tenant-id: ${{ secrets.AWS_PRD_TENANT_ID }}
          aws-prd-access-key-id: ${{ secrets.AWS_PRD_ACCESS_KEY_ID_IK_4 }}
          aws-prd-secret-access-key: ${{ secrets.AWS_PRD_SECRET_ACCESS_KEY_IK_4 }}
          aws-prd-region-name: eu-west-1          
         
